declare const VITE_MORALIS_APP_ID: string
declare const VITE_MORALIS_MASTER_KEY: string
declare const VITE_MORALIS_API_KEY: string
declare const VITE_MORALIS_SERVER_URL: string
declare const VITE_ALCHEMY_PRIVATE_API_KEY: string
declare const VITE_ALCHEMY_URL_PROVIDER: string
declare const VITE_STRIPE_PUBLIC_KEY: string
declare const VITE_STRIPE_PRIVATE_KEY: string
declare const VITE_STRIPE_PRODUCT_KNRT: string
declare const VITE_STRIPE_PRODUCT_MATIC: string
declare const VITE_STRIPE_PRODUCT_KNRT_TEST_CNRT: string
declare const VITE_CHAIN_ID_MAINNET: string
declare const VITE_CHAIN_ID_TESTNET: string
